### ISSUE TITLE
Links to example configuration and replay are dead

### ISSUE THREAD

**Issue by henrykrumb** [SciKit-Surgery/snappysonic#22]
Hi there,

this looks like a very nice project and I couldn't wait to get my hands on it. Unfortunately, I currently do not have access to a replay of U/S data nor a config, which apparently are necessary to test the simulator.

According to the README:
"An example configuration file can be downloaded from [here](https://github.com/SciKit-Surgery/snappysonic/config.json) and an image buffer from [source code repository data directory](https://github.com/SciKit-Surgery/snappysonic/data)"

However, both of the URLs 404 when I try to open them. Are the files still available, so they can be shared in a different place?

Many thanks in advance!

**Comment by thompson318** [comment]
Sorry, there's a few things in here that need updating. For config try https://github.com/SciKit-Surgery/snappysonic/blob/master/config.json and for data try https://github.com/SciKit-Surgery/snappysonic/tree/master/data
Let me know how you get on, then we can update the docs.
